const hasOrziceToken = Boolean(process.env.ORZICE_TOKEN)
const hasDeltaForceApiKey = Boolean(process.env.DELTA_FORCE_API_KEY)

export const sourceRegistry = [
  {
    id: 'steam-delta-force-news',
    name: 'Steamworks · Delta Force 公告',
    owner: 'Valve / Delta Force publisher',
    server: ['level-infinite'],
    datasets: ['events', 'announcements'],
    type: 'OFFICIAL_DISTRIBUTION_API',
    method: 'documented-json-api',
    url: 'https://partner.steamgames.com/doc/webapi/ISteamNews',
    endpoint: 'https://api.steampowered.com/ISteamNews/GetNewsForApp/v2/',
    enabled: true,
    legalStatus: 'public-documented',
    refreshMinutes: 15,
  },
  {
    id: 'garena-official-news',
    name: 'Garena Delta Force 官方公告',
    owner: 'Garena',
    server: ['garena'],
    datasets: ['events', 'announcements'],
    type: 'OFFICIAL_PUBLIC_PAGE',
    method: 'cached-html',
    url: 'https://deltaforce.garena.com/en/news/announcement',
    enabled: true,
    legalStatus: 'robots-allowed-public-page',
    refreshMinutes: 30,
  },
  {
    id: 'playdeltaforce-public-pages',
    name: 'Delta Force 全球官网公开页面',
    owner: 'Level Infinite',
    server: ['level-infinite'],
    datasets: ['patches', 'maps', 'static-game-data'],
    type: 'OFFICIAL_PUBLIC_PAGE',
    method: 'reviewed-snapshot',
    url: 'https://www.playdeltaforce.com/en/news/',
    enabled: false,
    legalStatus: 'robots-allowed-no-stable-structured-feed',
    note: 'robots.txt 允许抓取；当前只作为人工校验来源，未调用未公开的站内接口。',
  },
  {
    id: 'playdeltaforce-hq-public-data',
    name: 'Delta Force 官方 HQ 公开数据层',
    owner: 'Level Infinite',
    server: ['level-infinite'],
    datasets: ['passwords', 'items', 'weapons', 'slots', 'recipes', 'manufacture-recommendations', 'maps', 'operators', 'seasons', 'builds'],
    type: 'OFFICIAL_WEB_INTERNAL',
    method: 'cached-public-web-data',
    url: 'https://www.playdeltaforce.com/events/hq/en/',
    enabled: true,
    legalStatus: 'public-web-undocumented-endpoints',
    refreshMinutes: 5,
    note: '已接免登录密码、生产推荐及官网静态资料；低频服务端缓存。不是对第三方承诺的 Developer API，商业上线前仍需确认长期使用授权。',
  },
  {
    id: 'playdeltaforce-hq-shared-passwords',
    name: 'Delta Force 官方 HQ · 国际服共享每日密码',
    owner: 'Level Infinite / Garena channel',
    server: ['level-infinite', 'garena'],
    datasets: ['passwords'],
    type: 'OFFICIAL_WEB_INTERNAL',
    method: 'cached-public-web-data',
    url: 'https://www.playdeltaforce.com/events/hq/en/',
    enabled: true,
    legalStatus: 'public-web-undocumented-endpoint',
    refreshMinutes: 5,
    note: 'LI 与 Garena 使用同一密码值；按 UTC 00:00 日界线标记，结论由官方日界线与公开密码时间戳交叉验证。',
  },
  {
    id: 'deltaforceapi-commercial',
    name: 'DeltaForceAPI',
    owner: 'DeltaForceAPI',
    server: ['level-infinite'],
    datasets: ['items', 'market', 'price-history', 'maps', 'heroes', 'seasons', 'builds'],
    type: 'THIRD_PARTY_API',
    method: 'connectrpc-api-key',
    url: 'https://deltaforceapi.com/',
    enabled: hasDeltaForceApiKey,
    legalStatus: 'api-key-required-terms-pending',
    refreshMinutes: 1,
    note: hasDeltaForceApiKey
      ? '已配置 API Key；区服覆盖、商用授权、价格与 SLA 仍需与供应商书面确认。'
      : '代码适配已完成；配置 DELTA_FORCE_API_KEY 后启用。供应商未公开明确区服字段，默认不写入 Garena 或国服。',
  },
  {
    id: 'playdeltaforce-hq-garena-gun-codes',
    name: 'Delta Force 官方 HQ · Garena 改枪码',
    owner: 'Level Infinite / Garena channel',
    server: ['garena'],
    datasets: ['builds'],
    type: 'OFFICIAL_PUBLIC_STATIC_DATA',
    method: 'cached-public-static-js',
    url: 'https://www.playdeltaforce.com/events/hq/en/',
    enabled: true,
    legalStatus: 'public-web-undocumented-data-file',
    refreshMinutes: 60,
    note: '读取官网明确分离的 GA 渠道烽火地带与全面战场改枪码文件，不复用 LI 枪码。',
  },
  {
    id: 'orzice-open-platform',
    name: 'Orzice / 三角洲数据帝开放平台',
    owner: 'Orzice',
    server: ['cn'],
    datasets: ['items', 'market', 'passwords', 'builds', 'recipes', 'gear-value'],
    type: 'LICENSED_THIRD_PARTY',
    method: 'token-api',
    url: 'https://work-api.apifox.cn/',
    endpoint: 'https://orzice.com/workApi/v1/sjz_api/',
    enabled: hasOrziceToken,
    legalStatus: 'documented-token-required',
    note: hasOrziceToken ? '已配置服务端 Token。' : '未配置 ORZICE_TOKEN；不会匿名调用或抓取。',
    refreshMinutes: 10,
  },
  {
    id: 'local-reviewed-rules',
    name: '项目人工校验规则库',
    owner: 'Operations Desk',
    server: ['cn', 'level-infinite', 'garena'],
    datasets: ['maps', 'missions', 'recipes', 'gear-value'],
    type: 'MANUAL_VERIFIED',
    method: 'versioned-local-data',
    url: '/DATA_SOURCES.md',
    enabled: true,
    legalStatus: 'project-owned',
  },
  {
    id: 'demo-seed',
    name: '界面演示数据',
    owner: 'Operations Desk',
    server: ['cn', 'level-infinite', 'garena'],
    datasets: ['market', 'passwords', 'builds', 'recipes', 'missions'],
    type: 'DEMO',
    method: 'fallback-only',
    url: '/src/data.js',
    enabled: true,
    legalStatus: 'project-owned',
    note: '仅在没有合规上游时回退，响应会明确标记 demo。',
  },
]

export function publicSourceRegistry() {
  return sourceRegistry.map(({ endpoint, ...source }) => ({
    ...source,
    configured: source.id === 'orzice-open-platform'
      ? hasOrziceToken
      : source.id === 'deltaforceapi-commercial' ? hasDeltaForceApiKey : undefined,
  }))
}

export function sourceById(id) {
  return sourceRegistry.find((source) => source.id === id)
}
